<?php
return [
	'siteTitle' => 'Parts-Link - Stocks warehouses info',
	'siteLogo' => 'LOGO',
    'siteSave' => 'Save',
    'siteSearchingLbl' => 'Search through warehouses by part number',
    'searchLengthErr' => 'Length of entered number is not sufficient for searching',
	'siteSearchEmpty' => 'The requested number is not found on the stocks',
    'siteSearchCrossesShow' => 'Show founded crosses',
	'searchFor' => 'Search for...',
	'siteErrorLbl' => 'Error',
	
	// Menu
	'siteMenuAbout' => 'About this site',
	'siteMenuContact' => 'Write Us',
	'siteMenuLogin' => 'Login',
	'siteMenuLogout' => 'Logout',
    'siteMenuUser' => 'User',
    'siteTabProfile' => 'User\'s profile',
    'siteTabWarehouse' => 'User\'s Warehouses',
    'siteSelectorAccountActive' => 'Account is active',
	
	// Модальная форма Логина
	'siteLoginTitle' => 'Parts-Link Authorization',
	'siteLoginCloseBtn' => 'Dismiss',
	'siteLoginLoginBtn' => 'Login',
	'siteLoginNameLbl' => 'Your email*',
	'siteLoginPasswLbl' => 'Your password*',
	'siteLoginPassw2Lbl' => 'Repeat your password*',
    'siteLoginRegisterBtn' => 'I have no account yet, register me!',
    'siteLoginUserNot' => 'User does not registered yet',
    'siteLoginPasswErr' => 'Password Error',
    'siteLoginAccountErr' => 'Account is disabled',

    // Модальная форма Регистрации
    'siteRegisterTitle' => 'Register at Parts-Link',
    'siteRegisterRegisterBtn' => 'Register',
    'siteRegisterLoginBtn' => 'I have an account. Login me!',
	'siteRegisterConnErr' => 'Data connection Error',
	'siteRegisterLoginErr' => 'Email is needed for furthers logins by you',
	'siteRegisterPasswErr' => 'Password is required',
	'siteRegisterDublicateErr' => 'Entered Email is already registered by smb.',
	'siteRegisterAddErr' => 'Error adding new user',
	'siteRegisterWrongErr' => 'Something went wrong :(',
	'siteRegisterLoginPlace' => 'Enter your registration email here',
	'siteRegisterPasswPlace' => 'Enter your password',
	'siteRegisterPassw2Err' => 'Passwords are different',
	
	// Profile Page
	'profileConnErr' => 'Profile binding Error. Obviously, the server changed the session. Try Exit and Login. If the error persists, notify the portal administrator',
	'profileConfirmBtn' => 'Confirm',
	'profileConfirmLbl' => 'To confirm updating, enter your current valid password, please',
	'profileAccountAct' => 'You disable your account. Your warehouses will not be displayed.',
    'profileUpdateErr' => 'Profile is not updated',
    'profileAccountMenu' => 'Account',
    'profileStocksMenu' => 'Stocks',
    'profilePartsMenu' => 'Parts',
    'profileAccountDetail' => 'Account\'s detail',
    'profileAccountParams' => 'Account\'s parameters',
    'profileAccountPlan' => 'Type of account',
    'profileAccountLogins' => 'Name and login',
    'profileAccountName' => 'Name',
    'profileAccountFree' => 'Free of pay',
    'profileAccountId' => 'User Card ID:',
	'stockName' => 'Stock\'s name',
	'stockCountry' => 'Stock\'s country',
    'stockCountryCode' => 'Country code',
	'stockAdress' => 'Stock\'s adress',
	'stockCity' => 'Stock\'s city',
	'stockMultiError' => 'We\'ve found you have more than one Warehouse registered and Free of pay Type of Account. The first registered Warehouse is set as Active. To having more stocks you have to change your Type of Account',
	'profileActiveWarning' => 'Your Account is not set as Active. Actuality of your stocks will be unavailable for visiters.',
    'stockCurrency' => 'Stock\'s currency',
    'stockSelectorStockActive' => 'Stock is active',
    'stockOrdersEmail' => 'Stock\'s orders E-mail',
    'stockLocation' => 'Stock\'s location',
    'stockConacts' => 'Stock\'s contacts',
    'stockPhone' => 'Stock\'s phone',
    'stockPhoneAdd' => 'Add phone',
    'stockShipmentInfo' => 'Shipment info',
    'stockPhoneViberChk' => 'Check if this phone has Viber',
    'stockPhoneWhatsappChk' => 'Check if this phone has Whatsapp',
    'stockPartsQsearch' => 'Quick search by Number in the current warehouse',
	'stockPartsEmptyStock' => 'Your warehouse is empty yet',
];