<?php
return [
	'siteTitle' => 'Parts-Link информация о наличии на складах',
	'siteLogo' => 'ЛОГО',
    'siteSave' => 'Сохранить',
    'siteSearchingLbl' => 'Поиск на складах по каталожному номеру детали',
    'searchLengthErr' => 'Длины введенного номера не достаточно для поиска',
	'siteSearchEmpty' => 'Искомый номер в предложениях не найден',
    'siteSearchCrossesShow' => 'Показать найденные аналоги',
	'searchFor' => 'Номер для поиска...',
	
	// Меню
	'siteMenuAbout' => 'О платформе',
	'siteMenuContact' => 'Написать нам',
	'siteMenuLogin' => 'Войти',
	'siteMenuLogout' => 'Выйти',
    'siteMenuUser' => 'Пользователь',
    'siteTabProfile' => 'Профиль пользователя',
    'siteTabWarehouse' => 'Склады',
    'siteSelectorAccountActive' => 'Учетная запись активна',

	// Модальная форма Логина
	'siteLoginTitle' => 'Авторизация на Parts-Link',
	'siteLoginCloseBtn' => 'Закрыть',
	'siteLoginLoginBtn' => 'Войти',
	'siteLoginNameLbl' => 'Е-мейл*',
	'siteLoginPasswLbl' => 'Пароль*',
	'siteLoginPassw2Lbl' => 'Повтор пароля*',
    'siteLoginRegisterBtn' => 'У меня еще нет акаунта, зарегистрируйте!',
    'siteLoginUserNot' => 'Такой пользователь еще не зарегистрирован',
    'siteLoginPasswErr' => 'Неверный пароль',
    'siteLoginAccountErr' => 'Учетная запись выключена',

    // Модальная форма Регистрации
    'siteRegisterTitle' => 'Быстрая регистрация в Parts-Link',
    'siteRegisterRegisterBtn' => 'Зарегистрироваться',
    'siteRegisterLoginBtn' => 'У меня есть акаунт. Войти!',
	'siteRegisterConnErr' => 'Ошибка соединения',
	'siteRegisterLoginErr' => 'Ваш емейл необходим для входа на сайт',
	'siteRegisterPasswErr' => 'Пароль необходим',
	'siteRegisterDublicateErr' => 'Такой емейл уже зарегистрирован',
	'siteRegisterAddErr' => 'Ошибка добавления нового пользователя',
	'siteRegisterWrongErr' => 'Что-то пошло не так :(',
	'siteRegisterLoginPlace' => 'Введите Ваш емейл',
	'siteRegisterPasswPlace' => 'Введите Ваш пароль',
	'siteRegisterPassw2Err' => 'Пароли не совпадают',
	
	// Страница Профиль и Склады
	'profileConnErr' => 'Ошибка связи с профилем. Очевидно, сервер изменил сеанс. Попробуйте Выйти и Войти. Если ошибка повторится, сообщите администратору портала.',
	'profileConfirmBtn' => 'Подтвердить',
	'profileConfirmLbl' => 'Для подтверждения изменений, введите Ваш действующий пароль',
	'profileAccountAct' => 'Вы отключили Вашу учетную запись. Ваши склады не будут отображаться.',
    'profileUpdateErr' => 'Данные не изменены',
    'profileAccountMenu' => 'Профиль',
    'profileStocksMenu' => 'Склады',
    'profileAccountDetail' => 'Детали учетной записи',
    'profileAccountParams' => 'Параметры учетной записи',
    'profileAccountPlan' => 'Условия пользования',
    'profileAccountLogins' => 'Имя и данные',
    'profileAccountName' => 'Имя',
    'profileAccountFree' => 'Бесплатный',
    'profileAccountId' => 'Номер кода учетной записи:',
	'stockName' => 'Название склада',
	'stockMultiError' => 'Найдено более одного склада при Бесплатном Условии Использования. Активным будет Первый из зарегистрированных складов. Для использования более одного склада следует изменить Условие Использования',
	'profileActiveWarning' => 'Ваша Учетная Запись не установлена как Активная (на странице Профиль), поэтому наличие на Ваших складах не будет видно посетителям портала.',
];